language: node_js

node_js:
   "8.6.0"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  provider: npm
	skip_cleanup: true
  email: prithweedas123@gmail.com
  api_key: $npm_token
  name: Prithwee Das
  on:
    branch: master
